apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - target:
      kind: Deployment
    path: patches/add-jcasc.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: jenkins-config
    files:
      - assets/jenkins-config.yaml
