apiVersion: v1
data:
  desired-plugins.txt: "kubernetes:4306.vc91e951ea_eb_d\r\ngit:5.7.0"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: jenkins-dev
    app.kubernetes.io/version: "2.495"
  name: desired-plugins
  namespace: jenkins-dev
