apiVersion: route.openshift.io/v1
kind: Route

metadata:
  name: jenkins

spec:
  host: jenkins.apps-crc.testing
  to:
    kind: Service
    name: jenkins
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
