apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkins-dev
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: ci-cd-tool
    app.kubernetes.io/instance: jenkins-dev
    app.kubernetes.io/name: jenkins-master
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080